### ISSUE TITLE
You're setting some state, which I think is not supported.

### ISSUE THREAD

**Issue by biocomp** [bspranger/Hubitat_iComfort#3]
I'm new to hubitat scripts, so I can definitely be mistaken, then sorry :)

But it looks like here instead of making a local variable `def loginResult = ...`, you're setting some app-level property (which I think is not even really supported?)

https://github.com/bspranger/Hubitat_iComfort/blob/2f37fec2dcfab8300f47096db1f2a95856d2171a/App/Lennox-iComfort-connect.groovy#L55

**Comment by bspranger** [comment]
This is fixed.  Please grab the latest code
